### ISSUE TITLE
MUnrecognized error during join events prevents greeting messages from being sent

### ISSUE THREAD

**Issue by Protestdruck** [williamkray/maubot-communitybot#12]
We’re using maubot-communitybot v0.2.5 with a current Matrix stack (Synapse, Element, etc., all updated within the last week). The bot does not send greetings when users join rooms or spaces, and repeatedly throws an exception during the join event handler.

The traceback shows that an invalid GET /rooms/state call is being made, resulting in an MUnrecognized error. This occurs regardless of the configuration used.
### Example log excerpts (identifiers anonymized):
```scss
[2025-04-21 11:41:38,324] req #30490 (/v3/rooms/state) completed in 37.0ms with status 404  
[2025-04-21 11:41:38,325] Failed to run handler  
Traceback (most recent call last):  
  ...
  File ".../community/bot.py", line 193, in get_space_roomlist  
    state = await self.client.get_state(space)  
  ...
mautrix.errors.request.MUnrecognized: Unrecognized request
```
This pattern repeats multiple times. Each error is always preceded by a request to /v3/rooms/state without a room ID, which returns a 404 and causes the bot to throw.

Meanwhile, valid requests like:
```bash
GET /v3/rooms/%21adTiLgcTBRXngpDRpl%3Aexample.tld/state
```
…return 200 OK as expected.
### Configuration excerpt (anonymized):
```yaml
parent_room: '!adTiLgcTBRXngpDRpl:example.tld'
greetings:
  generic: |
    Welcome {user}! Please be sure to read the topic for helpful links and information.
greeting_rooms:
  '!iUJgXZKunsHrOxmOiK:example.tld': generic
notification_room: '!ZJDnlylrKoiFelGYCc:example.tld'
track_users: true
track_messages: true
track_reactions: true
...
```
This issue persists regardless of which room is listed under greeting_rooms, or whether the parent_room is used as a space or a regular room.

### Steps to Reproduce:
 
- Configure parent_room and greeting_rooms as shown above.
- Let a user join one of the managed rooms.
- Observe that no greeting message is sent.
- Review logs — each join event triggers a failing GET /rooms/state and an MUnrecognized exception.

### Expected Behavior:

The bot should greet users in rooms listed in greeting_rooms when they join.

### Actual Behavior:

The join handler fails due to an invalid API call, preventing greeting messages.
Let me know if I can provide additional logs or a minimal reproducible setup.

**Comment by williamkray** [comment]
hmm. this is very odd.

i have multiple instances of this bot running using the upstream maubot docker container, and have never seen this issue. a couple things stand out to me:

the bot reuses a function to get a list of rooms in the parent space, so i'm not surprised that your logs show repeated errors whenever this function is called.

when describing the error you mentioned "a request to /v3/rooms/state without a room ID". this function fetches the room ID of the space/parent room from the config, but if it's not using a valid value, then something is likely wrong with the config somewhere along the lines, specifically for the parent_room value.

alternatively, is it possible that the room you have listed as the parent_room has some sort of issue allowing your bot to fetch its state? maybe permissions, maybe the bot is not in that room, maybe there is a borked state history, something like that? this seems less likely, since the call to that endpoint would include the room id in the call most likely. i see plenty of successful calls to room state in my logs on my end, and they include the room in them.

i would experiment with the parent room id value, and if that doesn't surface something we could maybe throw some debug log lines in a few places and see if that helps narrow down what's actually going wrong.

**Comment by williamkray** [comment]
here's a version that includes some of the latest fixes, and puts some exception handling and debug logging around that get_space_roomlist function, see if this helps you chase this down in your logs:

[org.jobmachine.communitybot-v0.2.6.zip](https://github.com/user-attachments/files/19835918/org.jobmachine.communitybot-v0.2.6.zip)

**Comment by Protestdruck** [comment]
Hi again! Thanks a lot for taking the time to look into this and for providing the debugging patch – that was super helpful 🙏

Just to follow up, here’s what I got after applying the patch and restarting the container:

Logs after applying the patch:
```scss
[2025-04-21 15:26:55,077] [DEBUG@maubot.instance.strgleftcommunitybot] DEBUG getting roomlist from !adTiLgcTBRXngpDRpl:linkebonn.de space
[2025-04-21 15:26:55,079] [DEBUG@maubot.client.@bot.strgleft:linkebonn.de] req #56: GET http://synapse:8008/_matrix/client/v3/rooms/%21adTiLgcTBRXngpDRpl%3Alinkebonn.de/state None
[2025-04-21 15:26:55,098] [DEBUG@maubot.client.@bot.strgleft:linkebonn.de] req #56 (/v3/rooms/%21adTiLgcTBRXngpDRpl%3Alinkebonn.de/state) completed in 19.4ms with status 200
```


So that seems fine now!

However, when a user joins, the bot detects the event, but still no greeting message is posted.

Example:
```scss
[2025-04-21 15:28:02,964] [DEBUG@maubot.instance.strgleftcommunitybot] Sync stream leave event for @max.mustermann:linkebonn.de in !iUJgXZKunsHrOxmOiK:linkebonn.de detected
[2025-04-21 15:28:02,964] [DEBUG@maubot.instance.strgleftcommunitybot] membership change event for @max.mustermann:linkebonn.de in !iUJgXZKunsHrOxmOiK:linkebonn.de detected
[2025-04-21 15:28:09,970] [DEBUG@maubot.instance.strgleftcommunitybot] DEBUG getting roomlist from !adTiLgcTBRXngpDRpl:linkebonn.de space
```

```scss
[2025-04-21 15:40:23,586] [DEBUG@maubot.instance.strgleftcommunitybot] Sync stream leave event for @max.mustermann:linkebonn.de in !adTiLgcTBRXngpDRpl:linkebonn.de detected
[2025-04-21 15:40:23,586] [DEBUG@maubot.instance.strgleftcommunitybot] membership change event for @max.mustermann:linkebonn.de in !adTiLgcTBRXngpDRpl:linkebonn.de detected
[2025-04-21 15:40:28,034] [DEBUG@maubot.instance.strgleftcommunitybot] DEBUG getting roomlist from !adTiLgcTBRXngpDRpl:linkebonn.de space
```
Full config: 
```yaml
parent_room: '!adTiLgcTBRXngpDRpl:linkebonn.de'
sleep: 5
encrypt: false
warn_threshold_days: 30
kick_threshold_days: 60
track_users: true
track_messages: true
track_reactions: true
admins: []
moderators: []
invitees:
  - '@mybot:server.tld'
  - '@secondaryadmin:server.tld'
greetings:
  generic: |
    Welcome {user}! Please be sure to read the topic for helpful links and information.
    Use <a href="https://google.com">Google</a> for all other queries ;)
greeting_rooms:
  '!iUJgXZKunsHrOxmOiK:linkebonn.de': generic
  '!adTiLgcTBRXngpDRpl:linkebonn.de': generic
welcome_sleep: 0
notification_room: '!ZJDnlylrKoiFelGYCc:linkebonn.de'
join_notification_message: |
  User <code>{user}</code> has joined <code>{room}</code>.
censor: false
uncensor_pl: 1
censor_files: true
censor_wordlist:
  - effword
  - essword
censor_wordlist_instaban: []
banlists:
  - '#community-moderation-effort-bl:neko.dev'
proactive_banning: true
redact_on_ban: true
check_if_human: false
verification_phrases:
  - Yes, I am a human!
  - I am a robot, but I'm nice.
  - My name is Inigo Montoya.
  - The wet bird flies at night.
  - Be excellent to each other.
  - Party on, dudes.
verification_attempts: 3
verification_message: |-
  Thank you for joining {room}. As an anti-spam measure, you must demonstrate that you are a real person before you can send messages in its rooms.

  Please send a message to this chat with the phrase: "{phrase}"
```

Setup summary

- `!adTiLgcTBRXngpDRpl:linkebonn.de` is just a regular room, not a space – used as parent_room
- `!iUJgXZKunsHrOxmOiK:linkebonn.de` is a room within a space
- Bot is present in both rooms
- !community commands like !community roomid work as expected
- The generic greeting is set for both rooms via greeting_rooms

Let me know if there's anything else I can test or try out. I'm happy to help debug further!

Thanks again for your time 🙏
